config/routes.rb
Rails.application.routes.draw do
  resources :models
  resources :applications

  root to: "applications#index"
end

app/models/action.rb
class Action < ActiveRecord::Base
end

# == Schema Information
#
# Table name: actions
#
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  name       :string
#  updated_at :datetime         not null
#

app/models/application.rb
class Application < ActiveRecord::Base

  has_many :models

end

# == Schema Information
#
# Table name: applications
#
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  name       :string
#  updated_at :datetime         not null
#

app/models/field.rb
class Field < ActiveRecord::Base

  belongs_to :model

  enum attr_type: [
    :reference, :string, :text, :integer, :float, :decimal,
    :datetime, :timestamp, :time, :date, :binary, :boolean
  ]

  validates_presence_of :attr_type, :name

end

# == Schema Information
#
# Table name: fields
#
#  attr_type  :integer
#  created_at :datetime         not null
#  default    :string
#  id         :integer          not null, primary key
#  model_id   :integer
#  name       :string
#  required   :boolean
#  updated_at :datetime         not null
#

app/models/model.rb
class Model < ActiveRecord::Base

  belongs_to :application

  has_many :fields, dependent: :destroy
  accepts_nested_attributes_for :fields, reject_if: :all_blank, allow_destroy: true

  has_and_belongs_to_many :actions

end

# == Schema Information
#
# Table name: models
#
#  application_id :integer
#  created_at     :datetime         not null
#  id             :integer          not null, primary key
#  name           :string
#  updated_at     :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :has_devise, :has_api)
    end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:name, :application_id,
        fields_attributes: [:id, :name, :attr_type, :default, :required, :editable_by_user, :_destroy],
        action_ids: []
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/applications/_form.html.slim
= simple_form_for(@application) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :has_devise
    = f.input :has_api

  .form-actions
    = f.button :submit

app/views/applications/edit.html.slim
h1 Editing application

== render 'form'

= link_to 'Show', @application
'|
= link_to 'Back', applications_path

app/views/applications/index.html.slim
h1 Listing applications

table
  thead
    tr
      th Name
      th
      th
      th
      th

  tbody
    - @applications.each do |application|
      tr
        td = application.name
        td = link_to 'Show', application
        td = link_to 'JSON', application_path(application, format: :json), target: "_blank"
        td = link_to 'Edit', edit_application_path(application)
        td = link_to 'Destroy', application, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Application', new_application_path

app/views/applications/new.html.slim
h1 New application

== render 'form'

= link_to 'Back', applications_path

app/views/applications/show.html.slim
p#notice = notice

p
  strong Name:
  = @application.name

= link_to 'Edit', edit_application_path(@application)
'|
= link_to 'Back', applications_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
/ navigation styled for Zurb Foundation 5
nav.top-bar[data-topbar]
  ul.title-area
    li.name
      = link_to 'Home', root_path
    li.toggle-topbar.menu-icon
      a[href="#"]
        Menu
  .top-bar-section
    ul
      == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li= link_to "Applications", applications_path
li= link_to "Models", models_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Model Descriptor'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Model Descriptor'}"
    == stylesheet_link_tag "application", :media => 'all'
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/models/_field_fields.html.slim
.nested-fields
  = f.input :name
  = f.input :attr_type, as: :select, collection: Field.attr_types.keys, include_blank: false, selected: Field.attr_types.keys[f.object[:attr_type].to_i]
  = f.input :default
  = f.input :required
  = f.input :editable_by_user
  = link_to_remove_association "remove field", f
  br
  br

app/views/models/_form.html.slim
= simple_form_for(@model) do |f|
  = f.error_notification

  p
    h4 Reglas
    | 1. Utilice solamente las acciones de controlador necesarias. Si es un modelo headless, ninguna.
    br
    | 2. Las referencias no son del tipo model_id:references, sino model:references. No le ponga el _id.
    br
    | 3. Por ahora no estoy procesando default, required o editable. No se moleste en ponerlo.

  br

  .form-inputs
    = f.input :name
    = f.association :application, collection: Application.all, value_method: :id, label_method: :name, include_blank: false
    = f.input :action_ids, as: :check_boxes, label: "Actions", collection: Action.all, value_method: :id, label_method: :name

    h3 Fields
    = f.simple_fields_for :fields do |field|
      = render 'field_fields', f: field
    .links
      = link_to_add_association 'add field', f, :fields

  .form-actions
    = f.button :submit

app/views/models/edit.html.slim
h1 Editing model

== render 'form'

= link_to 'Show', @model
'|
= link_to 'Back', models_path

app/views/models/index.html.slim
h1 Listing models

table
  thead
    tr
      th Name
      th Application
      th
      th
      th

  tbody
    - @models.each do |model|
      tr
        td = model.name
        td = model.application.name
        td = link_to 'Show', model
        td = link_to 'Edit', edit_model_path(model)
        td = link_to 'Destroy', model, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Model', new_model_path

app/views/models/new.html.slim
h1 New model

== render 'form'

= link_to 'Back', models_path

app/views/models/show.html.slim
p#notice = notice

p
  strong Name:
  = @model.name
p
  strong Application:
  = @model.application.name
p
  strong Actions:
  = @model.actions.map(&:name).join(", ")
p
  strong Fields
  ul
    - @model.fields.each do |field|
      li
        p
          label Name
          = field.name
        p
          label Type
          = field.attr_type
        p
          label Default Value
          = field.default
        p
          label Required?
          = field.required.to_s

= link_to 'Edit', edit_model_path(@model)
'|
= link_to 'Back', models_path